// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxnghllunehjhkydkzid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bmdobGx1bmVoamhreWRremlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzMzMDksImV4cCI6MjA2NTQwOTMwOX0.smrKcCyKxgn5RcpOmswdkBAGOssLEqhodfTMPHk61OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);